version: '3.8'

services:
  tunnel_ssh:
    image: cloudflare/cloudflared:latest
    container_name: swift_tunnel_server
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # [수정 1] 공유 네트워크에 참여시킵니다.
    networks:
      - shared_api_network
    restart: always

# [수정 2] 외부에서 생성된 네트워크를 정의합니다.
networks:
  shared_api_network:
    external: true